name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: src
          file: Dockerfile
          push: true
          tags: |
            tallesalencar/rotten-potatoes:latest
            tallesalencar/rotten-potatoes:${{ github.run_number }}
            
